language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9-dev"

# command to install dependencies
install:
  - pip install -r requirements.testing.txt
  - pip install -e .

# command to run tests
script:
  - py.test -s -v --cov-report xml --cov=mergerpy
  - codecov
